/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author victo
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EventSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("EventSystemPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jpanel_telaPrincipal = new javax.swing.JPanel();
        jPanel_edicao = new javax.swing.JPanel();
        jPanel_consultar = new javax.swing.JPanel();
        btnNovoEspaco = new javax.swing.JButton();
        btnNovaSala = new javax.swing.JButton();
        btnNovoAluno = new javax.swing.JButton();
        btn_consultaAlunos = new javax.swing.JButton();
        btn_consultaSalas = new javax.swing.JButton();
        btn_consultaEspaco = new javax.swing.JButton();
        jLabel_tituloPainel = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FundoTela1");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel_consultarLayout = new javax.swing.GroupLayout(jPanel_consultar);
        jPanel_consultar.setLayout(jPanel_consultarLayout);
        jPanel_consultarLayout.setHorizontalGroup(
            jPanel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        jPanel_consultarLayout.setVerticalGroup(
            jPanel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        btnNovoEspaco.setText("Novo Espaço");
        btnNovoEspaco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovoEspaco.setMaximumSize(new java.awt.Dimension(80, 20));
        btnNovoEspaco.setMinimumSize(new java.awt.Dimension(80, 20));
        btnNovoEspaco.setPreferredSize(new java.awt.Dimension(80, 20));
        btnNovoEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEspacoActionPerformed(evt);
            }
        });

        btnNovaSala.setText("Nova Sala");
        btnNovaSala.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovaSala.setMaximumSize(new java.awt.Dimension(80, 20));
        btnNovaSala.setMinimumSize(new java.awt.Dimension(80, 20));
        btnNovaSala.setPreferredSize(new java.awt.Dimension(80, 20));
        btnNovaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaSalaActionPerformed(evt);
            }
        });

        btnNovoAluno.setText("Novo Aluno");
        btnNovoAluno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovoAluno.setMaximumSize(new java.awt.Dimension(80, 20));
        btnNovoAluno.setMinimumSize(new java.awt.Dimension(80, 20));
        btnNovoAluno.setPreferredSize(new java.awt.Dimension(80, 20));
        btnNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlunoActionPerformed(evt);
            }
        });

        btn_consultaAlunos.setText("Alunos Cadastrados");
        btn_consultaAlunos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_consultaAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaAlunosActionPerformed(evt);
            }
        });

        btn_consultaSalas.setText("Salas Cadastradas");
        btn_consultaSalas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_consultaSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaSalasActionPerformed(evt);
            }
        });

        btn_consultaEspaco.setText("Espaços Cadastrados");
        btn_consultaEspaco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_consultaEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaEspacoActionPerformed(evt);
            }
        });

        jLabel_tituloPainel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        jLabel_tituloPainel.setText(" Cadastro");
        jLabel_tituloPainel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_tituloPainel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_tituloPainel.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel_edicaoLayout = new javax.swing.GroupLayout(jPanel_edicao);
        jPanel_edicao.setLayout(jPanel_edicaoLayout);
        jPanel_edicaoLayout.setHorizontalGroup(
            jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_edicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_consultaEspaco, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(btn_consultaSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_consultaAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(149, 149, 149)
                .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_edicaoLayout.createSequentialGroup()
                        .addComponent(btnNovaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314)
                        .addComponent(jPanel_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel_edicaoLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel_tituloPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_edicaoLayout.setVerticalGroup(
            jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_edicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_tituloPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultaAlunos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_edicaoLayout.createSequentialGroup()
                        .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultaSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_edicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_consultaEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovoEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpanel_telaPrincipalLayout = new javax.swing.GroupLayout(jpanel_telaPrincipal);
        jpanel_telaPrincipal.setLayout(jpanel_telaPrincipalLayout);
        jpanel_telaPrincipalLayout.setHorizontalGroup(
            jpanel_telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        jpanel_telaPrincipalLayout.setVerticalGroup(
            jpanel_telaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jpanel_telaPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaSalaActionPerformed
        CadastroSalas cSalas = new CadastroSalas();
        cSalas.setVisible(true);
    }//GEN-LAST:event_btnNovaSalaActionPerformed

    private void btnNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlunoActionPerformed
        CadastroAluno cAluno = new CadastroAluno();
        cAluno.setVisible(true);
    }//GEN-LAST:event_btnNovoAlunoActionPerformed

    private void btnNovoEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEspacoActionPerformed
        CadastroEspacoCafe cEspaco = new CadastroEspacoCafe();
        cEspaco.setVisible(true);
    }//GEN-LAST:event_btnNovoEspacoActionPerformed

    private void btn_consultaAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaAlunosActionPerformed
        TabelaAlunos tAlunos = new TabelaAlunos();
        tAlunos.setVisible(true);
    }//GEN-LAST:event_btn_consultaAlunosActionPerformed

    private void btn_consultaSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaSalasActionPerformed
        TabelaSalas tSalas = new TabelaSalas();
        tSalas.setVisible(true);
    }//GEN-LAST:event_btn_consultaSalasActionPerformed

    private void btn_consultaEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaEspacoActionPerformed
        TabelaEspacoCafe tEspaco = new TabelaEspacoCafe();
        tEspaco.setVisible(true);
    }//GEN-LAST:event_btn_consultaEspacoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager EventSystemPUEntityManager;
    private javax.swing.JButton btnNovaSala;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnNovoEspaco;
    private javax.swing.JButton btn_consultaAlunos;
    private javax.swing.JButton btn_consultaEspaco;
    private javax.swing.JButton btn_consultaSalas;
    private javax.swing.JLabel jLabel_tituloPainel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel_consultar;
    private javax.swing.JPanel jPanel_edicao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel_telaPrincipal;
    // End of variables declaration//GEN-END:variables
}
