/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import model.IdCompostoAlunoEtapaEspaco;
import model.IdCompostoAlunoEtapaSala;
import model.SalasEntity;
import repository.AlunoEtapaEspacoRep;
import repository.AlunoEtapaSalaRep;
import repository.SalasRep;



/**
 *
 * @author victo
 */
public class ViewEvento extends javax.swing.JFrame {

    /**
     * Creates new form ViewEvento
     */
    public ViewEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        EventSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("EventSystemPU").createEntityManager();
        salasQuery = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT s FROM Salas s");
        salasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : salasQuery.getResultList();
        alunosQuery = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT a FROM Alunos a");
        alunosList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : alunosQuery.getResultList();
        espacoQuery = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT e FROM Espaco e");
        espacoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : espacoQuery.getResultList();
        etapaQuery = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT e FROM Etapa e");
        etapaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : etapaQuery.getResultList();
        alunosQuery1 = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT a FROM Alunos a");
        alunosList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : alunosQuery1.getResultList();
        salasQuery1 = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT s FROM Salas s");
        salasList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : salasQuery1.getResultList();
        espacoQuery1 = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT e FROM Espaco e");
        espacoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : espacoQuery1.getResultList();
        etapaQuery1 = java.beans.Beans.isDesignTime() ? null : EventSystemPUEntityManager.createQuery("SELECT e FROM Etapa e");
        etapaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : etapaQuery1.getResultList();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        txtSala = new javax.swing.JTextField();
        txtAluno = new javax.swing.JTextField();
        txtIntervalo = new javax.swing.JTextField();
        txtEtapa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGerarEtapa2 = new javax.swing.JButton();
        btnLimparEt2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evento");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        btnSalvar.setText("Gerar Etapa1");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Sala");

        jLabel2.setText("Intervalo");

        jLabel3.setText("Aluno");

        jLabel5.setText("Etapa");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, alunosList1, tblAlunos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idaluno}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomealuno}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sobrenome}"));
        columnBinding.setColumnName("Sobrenome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblAlunos);
        if (tblAlunos.getColumnModel().getColumnCount() > 0) {
            tblAlunos.getColumnModel().getColumn(0).setResizable(false);
            tblAlunos.getColumnModel().getColumn(1).setResizable(false);
            tblAlunos.getColumnModel().getColumn(2).setResizable(false);
        }

        txtSala.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JTable(), org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idsala}"), txtSala, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtAluno.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblAlunos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idaluno}"), txtAluno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtIntervalo.setEnabled(false);

        txtEtapa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtEtapa.setText("1");
        txtEtapa.setEnabled(false);

        jLabel6.setText("Alunos");

        btnGerarEtapa2.setText("Gerar Etapa2");
        btnGerarEtapa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarEtapa2ActionPerformed(evt);
            }
        });

        btnLimparEt2.setText("Limpar Etapa2");
        btnLimparEt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSala)
                            .addComponent(txtAluno)
                            .addComponent(txtIntervalo)
                            .addComponent(txtEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerarEtapa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimparEt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIntervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(47, 47, 47)
                        .addComponent(btnLimparEt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerarEtapa2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean CadastradoEtapa1(){
        boolean cadastrado = false;
        List<IdCompostoAlunoEtapaEspaco> checarRegistro = new AlunoEtapaEspacoRep().listar();
        for (int i = 0; i < checarRegistro.size(); i++) {
            if (txtAluno.getText().equals(checarRegistro.get(i).getIdAluno()) && txtEtapa.getText().equals("1")){
                    
                    cadastrado = true;
            }        
        }
        return cadastrado;
    }
    

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        //Definir média de alunos nos espaços de café
        List<IdCompostoAlunoEtapaEspaco> checarEspaco1 = new AlunoEtapaEspacoRep().listarPorIdEspacoComposto(1, 1);
        int alunosEspaco1 = checarEspaco1.size();

        List<IdCompostoAlunoEtapaEspaco> checarEspaco2 = new AlunoEtapaEspacoRep().listarPorIdEspacoComposto(2, 1);
        int alunosEspaco2 = checarEspaco2.size();     

        int soma = alunosEspaco1 + alunosEspaco2;

        int resto = soma % 2;

        if(resto == 0){
            txtIntervalo.setText("2");
        }else{
            txtIntervalo.setText("1");
        }
        
        //Definir Média de alunos nas Salas
        List<IdCompostoAlunoEtapaSala> checarSala1 = new AlunoEtapaSalaRep().listarPorIdSalaComposto(1, 1);
        int alunosSala1 = checarSala1.size();

        List<IdCompostoAlunoEtapaSala> checarSala2 = new AlunoEtapaSalaRep().listarPorIdSalaComposto(2, 1);
        int alunosSala2 = checarSala2.size();    

        int soma2 = alunosSala1 + alunosSala2;

        int resto2 = soma2 % 2;

        if(resto2 == 0){
            txtSala.setText("2");
        }else{
            txtSala.setText("1");
        }
        
        if(txtAluno.getText().equals("") || txtEtapa.getText().equals("") || txtIntervalo.getText().equals("") || txtSala.getText().equals("")){
            JOptionPane.showMessageDialog(this," Selecione o Aluno! " );
           
        }else if(!CadastradoEtapa1()){
           AlunoEtapaEspacoRep aee = new AlunoEtapaEspacoRep();
           IdCompostoAlunoEtapaEspaco idE = new IdCompostoAlunoEtapaEspaco();

           idE.setIdAluno(Integer.parseInt(txtAluno.getText()));
           idE.setIdEspaco(Integer.parseInt(txtIntervalo.getText()));
           idE.setIdEtapa(Integer.parseInt(txtEtapa.getText()));

           AlunoEtapaSalaRep aes = new AlunoEtapaSalaRep();
           IdCompostoAlunoEtapaSala idS = new IdCompostoAlunoEtapaSala();

           idS.setIdAluno(Integer.parseInt(txtAluno.getText()));
           idS.setIdSala(Integer.parseInt(txtSala.getText()));
           idS.setIdEtapa(Integer.parseInt(txtEtapa.getText()));

           aee.setId(idE);
           aes.setId(idS);
           aee.adicionar(aee);
           aes.adicionar(aes);
        }else{
            JOptionPane.showMessageDialog(this, "Aluno já Registrado nesta Etapa");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private int RandomID(){
        Random idAleatorio = new Random();
        int id = 0;
        for (int i = 0; i < 1; i++) {
            id = 1+idAleatorio.nextInt(2);
            System.out.println(id);
        }
        return id;
    }
    
    private void btnGerarEtapa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarEtapa2ActionPerformed
        AlunoEtapaSalaRep aes = new AlunoEtapaSalaRep();
        IdCompostoAlunoEtapaSala idS = new IdCompostoAlunoEtapaSala();
        
        AlunoEtapaEspacoRep aee = new AlunoEtapaEspacoRep();
        IdCompostoAlunoEtapaEspaco idE = new IdCompostoAlunoEtapaEspaco();
        
        List<IdCompostoAlunoEtapaSala> listaIds = new AlunoEtapaSalaRep().listar();
        boolean cadastrado = false;
        
        for (int i = 0; i < listaIds.size(); i++) {
            if (listaIds.get(i).getIdEtapa() == 2){
                cadastrado = true;
            }else if(!cadastrado){
                idE.setIdEtapa(2);
                idS.setIdEtapa(2);
                idS.setIdSala(RandomID());
                idS.setIdAluno(listaIds.get(i).getIdAluno());
                idE.setIdAluno(listaIds.get(i).getIdAluno());
                idE.setIdEspaco(RandomID());

                aee.setId(idE);
                aes.setId(idS);
                aes.adicionar(aes);
                aee.adicionar(aee); 
            }
        }
        
        if(!cadastrado){
            JOptionPane.showMessageDialog(this, "Todos os alunos foram Distribuidos entre as salas e espaços de café na etapa 2");
        }else{
            JOptionPane.showMessageDialog(this, "Alunos já Registrado nesta Etapa");
        }
    }//GEN-LAST:event_btnGerarEtapa2ActionPerformed

    private void btnLimparEt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEt2ActionPerformed
        AlunoEtapaSalaRep aes = new AlunoEtapaSalaRep();
        AlunoEtapaEspacoRep aee = new AlunoEtapaEspacoRep();
        
        aee.excluirEtapa2(aee);
        aes.excluirEtapa2(aes);
        JOptionPane.showMessageDialog(this, "Todos os alunos foram Retirados da etapa 2");
    }//GEN-LAST:event_btnLimparEt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager EventSystemPUEntityManager;
    private java.util.List<repository.Alunos> alunosList;
    private java.util.List<repository.Alunos> alunosList1;
    private javax.persistence.Query alunosQuery;
    private javax.persistence.Query alunosQuery1;
    private javax.swing.JButton btnGerarEtapa2;
    private javax.swing.JButton btnLimparEt2;
    private javax.swing.JButton btnSalvar;
    private java.util.List<repository.Espaco> espacoList;
    private java.util.List<repository.Espaco> espacoList1;
    private javax.persistence.Query espacoQuery;
    private javax.persistence.Query espacoQuery1;
    private java.util.List<repository.Etapa> etapaList;
    private java.util.List<repository.Etapa> etapaList1;
    private javax.persistence.Query etapaQuery;
    private javax.persistence.Query etapaQuery1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<repository.Salas> salasList;
    private java.util.List<repository.Salas> salasList1;
    private javax.persistence.Query salasQuery;
    private javax.persistence.Query salasQuery1;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtEtapa;
    private javax.swing.JTextField txtIntervalo;
    private javax.swing.JTextField txtSala;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
